apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service-app
  namespace: supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      containers:
      - name: supplier-service
        image: https://hub.docker.com/r/edwinhc93/medisupply-supplier-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: spring.application.name
          value: "IngresoBodega"
        - name: server.port
          value: "8081"
        - name: spring.kafka.bootstrap-servers
          value: "kafka-ingresobodega.bod.svc.cluster.local:9092"
        - name: spring.kafka.consumer.group-id
          value: group2
        - name: kafka.group.all
          value: group2
        - name: aws.region
          value: us-east-2
        - name: aws.accessKey
          value: 
        - name: aws.secretKey
          value: 
        - name: kafka.topic.inventario-recibido
          value: InventarioRecibido
        - name: kafka.topic.inventario
          value: InventarioActualizado