apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service-app
  namespace: supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      containers:
      - name: supplier-purcharse-service
        image: edwinhc93/medisupply-supplier-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: PORT
          value: "8080"
        - name: DYNAMODB_ENDPOINT
          value:
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq.supplier-service.svc.cluster.local:5672/"