apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-service-app
  namespace: purchase-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase-service
  template:
    metadata:
      labels:
        app: purchase-service
    spec:
      containers:
      - name: supplier-purcharse-service
        image: medisupply-purchase-order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DYNAMODB_ENDPOINT
          value: "http://dynamo-db.dynamo-service.svc.cluster.local:8000"
        - name: RABBITMQ_URL
          value: "amqp://admin:admin123@rabbitmq-broker-service.rabbitmq-broker.svc.cluster.local:5672/"
        - name: "SUPPLIER_SERVICE_URL"
          value: "http://supplier-service.supplier-service.svc.cluster.local:8080"