apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: default
  labels:
    app: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: public.ecr.aws/n7w5a8q2/notifications:v1
        imagePullPolicy: IfNotPresent   # 👈 usa tu imagen local de minikube
        ports:
        - containerPort: 9020
        env:
        - name: "spring.kafka.bootstrap-servers"
          value: "kafka-supply-broker.kafka-broker.svc.cluster.local:9092"
        - name: "spring.kafka.properties.allow.auto.create.topics"
          value: "true"
        - name: "logging.level.root"
          value: "DEBUG"
        - name: "logging.level.org.springframework.web"
          value: "DEBUG"
        - name: "logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping"
          value: "DEBUG"