apiVersion: v1
kind: Service
metadata:
  name: runtime-cluster-service
  namespace: default
spec:
  selector:
    app: eventmesh-runtime
  ports:
    - name: tcp
      port: 10000
      targetPort: 10000
      protocol: TCP
    - name: http
      port: 10105
      targetPort: 10105
      protocol: TCP
    - name: grpc
      port: 10205
      targetPort: 10205
      protocol: TCP
