apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":"2025-10-18T08:40:39Z","generation":31,"name":"eventmesh-runtime-0-a","namespace":"default","ownerReferences":[{"apiVersion":"eventmesh-operator.eventmesh/v1","blockOwnerDeletion":true,"controller":true,"kind":"Runtime","name":"eventmesh-runtime","uid":"a2fec64b-0623-4205-9d00-7d4229ab765f"}],"resourceVersion":"53143","uid":"09fbc794-cef4-41fa-b0f2-7821713648bb"},"spec":{"persistentVolumeClaimRetentionPolicy":{"whenDeleted":"Retain","whenScaled":"Retain"},"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"eventmesh-runtime"}},"serviceName":"","template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-10-18T10:32:03-05:00"},"creationTimestamp":null,"labels":{"app":"eventmesh-runtime"}},"spec":{"containers":[{"image":"alonexc/eventmesh-runtime:runtime-1.9.0","imagePullPolicy":"Always","name":"eventmesh-runtime","ports":[{"containerPort":10000,"name":"tcp","protocol":"TCP"},{"containerPort":10105,"name":"http","protocol":"TCP"},{"containerPort":10205,"name":"grpc","protocol":"TCP"}],"resources":{"limits":{"cpu":"8","memory":"8Gi"},"requests":{"cpu":"2","memory":"2Gi"}},"securityContext":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/app/eventmesh/conf","name":"runtime-config"},{"mountPath":"/data/app/eventmesh/lib","name":"eventmesh-lib"}]}],"dnsPolicy":"ClusterFirstWithHostNet","initContainers":[{"command":["sh","-c","echo \"Copiando conectores dentro de /data/app/eventmesh/lib ...\" \u0026\u0026 cp -vn /connectors/*.jar /data/app/eventmesh/lib/ \u0026\u0026 echo \"Contenido final de lib:\" \u0026\u0026 ls /data/app/eventmesh/lib;\n"],"image":"alonexc/eventmesh-runtime:runtime-1.9.0","imagePullPolicy":"IfNotPresent","name":"copy-connectors","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/connectors","name":"connectors-volume"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/conectores","type":"Directory"},"name":"connectors-volume"},{"configMap":{"defaultMode":420,"items":[{"key":"rocketmq.properties","path":"rocketmq.properties"},{"key":"eventmesh.properties","path":"eventmesh.properties"},{"key":"server.env","path":"server.env"},{"key":"log4j2.xml","path":"log4j2.xml"}],"name":"runtime-config"},"name":"runtime-config"}]}},"updateStrategy":{"type":"RollingUpdate"}},"status":{"availableReplicas":0,"collisionCount":0,"currentReplicas":1,"currentRevision":"eventmesh-runtime-0-a-66b85666fc","observedGeneration":31,"replicas":1,"updateRevision":"eventmesh-runtime-0-a-66b85666fc","updatedReplicas":1}}
  creationTimestamp: "2025-10-18T08:40:39Z"
  generation: 33
  name: eventmesh-runtime-0-a
  namespace: default
  ownerReferences:
  - apiVersion: eventmesh-operator.eventmesh/v1
    blockOwnerDeletion: true
    controller: true
    kind: Runtime
    name: eventmesh-runtime
    uid: a2fec64b-0623-4205-9d00-7d4229ab765f
  resourceVersion: "53300"
  uid: 09fbc794-cef4-41fa-b0f2-7821713648bb
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eventmesh-runtime
  serviceName: ""
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-18T10:41:37-05:00"
      creationTimestamp: null
      labels:
        app: eventmesh-runtime
    spec:
      containers:
      - image: alonexc/eventmesh-runtime:runtime-1.9.0
        imagePullPolicy: Always
        name: eventmesh-runtime
        ports:
        - containerPort: 10000
          name: tcp
          protocol: TCP
        - containerPort: 10105
          name: http
          protocol: TCP
        - containerPort: 10205
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: "8"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 2Gi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/app/eventmesh/conf
          name: runtime-config
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      - command:
        - sh
        - -c
        - |
          echo "Copiando conectores dentro de /data/app/eventmesh/lib ..." && cp -vn /connectors/*.jar /data/app/eventmesh/lib/ && echo "Contenido final de lib:" && ls /data/app/eventmesh/lib;
        image: alonexc/eventmesh-runtime:runtime-1.9.0
        imagePullPolicy: IfNotPresent
        name: copy-connectors
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /connectors
          name: connectors-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /conectores
          type: Directory
        name: connectors-volume
      - configMap:
          defaultMode: 420
          items:
          - key: rocketmq.properties
            path: rocketmq.properties
          - key: eventmesh.properties
            path: eventmesh.properties
          - key: server.env
            path: server.env
          - key: log4j2.xml
            path: log4j2.xml
          name: runtime-config
        name: runtime-config
  updateStrategy:
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentRevision: eventmesh-runtime-0-a-66b85666fc
  observedGeneration: 33
  replicas: 0
  updateRevision: eventmesh-runtime-0-a-7bbc8c4475
