apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connector
  template:
    metadata:
      labels:
        app: kafka-connector
    spec:
      containers:
      - name: kafka-connector
        image: openjdk:17-jdk-slim
        command: ["java", "-cp", "/app/connectors/*", "org.apache.eventmesh.connector.kafka.server.KafkaServer"]
        volumeMounts:
        - name: connector-volume
          mountPath: /app/connectors
        - name: config-volume
          mountPath: /app/conf
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-service.kafka-broker:9092"
      volumes:
      - name: connector-volume
        hostPath:
          path: /mnt/c/Users/Administrador/Desktop/uniandes/arquitectura/istio/manifiestos/eventmesh/eventmesh/eventmesh-connectors/eventmesh-connector-kafka/build/libs
      - name: config-volume
        hostPath:
          path: /mnt/c/Users/Administrador/Desktop/uniandes/arquitectura/istio/manifiestos/eventmesh/eventmesh/eventmesh-connectors/eventmesh-connector-kafka/src/main/resources
