apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-supply
  namespace: kafka-broker
  labels:
    app: kafka-supply
spec:
  serviceName: "kafka-supply"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-supply
  template:
    metadata:
      labels:
        app: kafka-supply
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
              name: kafka-supply
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-supply-broker.kafka-broker.svc.cluster.local:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-supply-broker.kafka-broker.svc.cluster.local:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_CLUSTER_ID
              value: "Gb3kC4xkQte6V9A0JQ5YAg"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-broker
data:
  # Kafka requires a stable cluster ID in KRaft mode
  cluster.id: "Gb3kC4xkQte6V9A0JQ5YAg"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-supply-broker
  namespace: kafka-broker
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  selector:
    app: kafka-supply