apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-test-consumer
  namespace: move-supply
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-test-consumer
  template:
    metadata:
      labels:
        app: kafka-test-consumer
    spec:
      containers:
        - name: kafka-test-consumer
          image: apache/kafka:3.7.0
          command:
            - bash
            - -c
            - |
              echo "🟢 Iniciando consumer de prueba en move-supply...";
              /opt/kafka/bin/kafka-console-consumer.sh \
                --bootstrap-server kafka-supply-broker.kafka-broker.svc.cluster.local:9092 \
                --topic FallaCadenaDeFrio \
                --group grupo-2 \
                --from-beginning
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
